- pom.xml
- src/it/MINVOKER-191/pom.xml
- src/it/MINVOKER-196_junit_report_file/pom.xml
- src/it/MINVOKER-196_junit_report_file/src/it/project/pom.xml
- src/it/MINVOKER-196_junit_report_file/src/it/project/verify.groovy
- src/it/MINVOKER-196_junit_report_file/src/it/project_2/pom.xml
- src/it/MINVOKER-196_junit_report_file/src/it/project_2/verify.groovy
- src/it/MINVOKER-196_junit_report_file/src/it/settings.xml
- src/it/MINVOKER-196_junit_report_file/verify.groovy
- src/it/pom-filtering-reactor/pom.xml
- src/it/script-errors/pom.xml
- src/it/skip-run/pom.xml
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
Signed-off-by: olivier lamy <olamy@apache.org>
> [MINVOKER-196] Support for JUnit report style

- src/main/java/org/apache/maven/plugins/invoker/InstallMojo.java
Signed-off-by: olivier lamy <olamy@apache.org>
> [MINVOKER-249] InstallMojo extraArtifacts are always downloaded (optionally local repo must checked first)

- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
this information doesn't have any context in build output
> some log is too more verbose in normal run

- pom.xml
As [3.2.2](https://issues.apache.org/jira/projects/MINVOKER/versions/12346157) is still unreleased, I think this change can be covered by [MINVOKER-254](https://issues.apache.org/jira/browse/MINVOKER-254).
[Changes in Groovy 2.4.19](http://groovy-lang.org/changelogs/changelog-2.4.19.html)
> [MINVOKER-254] Bump groovy to the latest in 2.4

- pom.xml
- src/it/invocation-environmentvariable/invoker.properties
- src/it/invocation-environmentvariable/src/it/minvoker-273/pom.xml
- src/it/invocation-environmentvariable/verify.groovy
After fix in `maven-shared-utils` we only need some tests for confirmation.
> [MINVOKER-273] Environment variable with empty value

- pom.xml
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/FileLogger.java
- src/main/java/org/apache/maven/plugins/invoker/InstallMojo.java
- src/main/java/org/apache/maven/plugins/invoker/MetadataUtils.java
- src/main/java/org/apache/maven/plugins/invoker/Selector.java
- src/main/java/org/apache/maven/plugins/invoker/SelectorUtils.java
- src/test/java/org/apache/maven/plugins/invoker/InterpolationTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerMojoTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
- src/test/java/org/apache/maven/plugins/invoker/SelectorUtilsTest.java
> [MINVOKER-281] java 8 as minimum

- pom.xml
> [MINVOKER-274] upgrade to groovy 3.0.8

- pom.xml
We should use the same version in project executions and site build
> maven-invoker-plugin version should be override in pluginManagement

- src/site/apt/examples/fast-use.apt.vm
`activeByDefault` does not work with extensions from `.mvn/extensions.xml`. It might also be more fragile, if other profiles are used, since it only has effect, if no other profiles are activated.
> Correct doc: Replace `activeByDefault` by `activeProfiles`.

- src/main/mdo/invocation.mdo
Similar:
- https://github.com/apache/maven-release/pull/102
Seems this upgrade to https was done on 2018-03-13 in several repositories, but no worries - I'm not going to track them all, that's the last one I do.
> Fix Modello namespace

- pom.xml
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/SelectorUtils.java
- src/test/java/org/apache/maven/plugins/invoker/SelectorUtilsTest.java
> [MINVOKER-297] NPE when non-existing Maven Home

- pom.xml
- src/site/site.xml
> [MINVOKER-301] Upgrade Parent to 36

- src/it/MINVOKER-288-failed-setup-run/invoker.properties
- src/it/MINVOKER-288-failed-setup-run/pom.xml
- src/it/MINVOKER-288-failed-setup-run/src/it/project1/pom.xml
- src/it/MINVOKER-288-failed-setup-run/src/it/project2/pom.xml
- src/it/MINVOKER-288-failed-setup-run/verify.groovy
- src/it/MINVOKER-288-failed-setup-verify/invoker.properties
- src/it/MINVOKER-288-failed-setup-verify/pom.xml
- src/it/MINVOKER-288-failed-setup-verify/src/it/project1/pom.xml
- src/it/MINVOKER-288-failed-setup-verify/src/it/project2/pom.xml
- src/it/MINVOKER-288-failed-setup-verify/verify.groovy
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/mdo/invocation.mdo
> [MINVOKER-288] Failed setup job cause skip rest of jobs

- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
> [MINVOKER-269] Execute forked Maven in quiet mode

- src/it/invocation-cmdline-exclude/src/it/minvoker-140-executable/pom.xml
- src/it/invocation-cmdline-exclude/src/it/minvoker-140-ignorable/pom.xml
- src/it/invocation-cmdline-exclude/test.properties
- src/it/invocation-cmdline-exclude/verify.groovy
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
In addition to [MINVOKER-140](https://issues.apache.org/jira/browse/MINVOKER-140): exclude patterns works only if one or more include pattern(s) exists. This is a feature of [plexus-utils Component DirectoryScanner](https://github.com/codehaus-plexus/plexus-utils/blob/3896620b4fbf031b1b02b4d46b328c5839a231da/src/main/java/org/codehaus/plexus/util/DirectoryScanner.java#L447-L449). 
So, in our case command line parameter <code>-Dinvoker.test=!testX</code> (and configuration parameter [invokerTest](https://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#invokerTest) ) works absolutely different way: **all projects** (not only testX) will be skipped. We must use <code>-Dinvoker.test=\*,!testX</code> or <code>-Dinvoker.test=!testX,\*</code> as workarround.
In this commit I add …
> [MINVOKER-306] - Fixed bug if only exclude-patterns specified

- src/it/MINVOKER-289/pom.xml
- src/it/MINVOKER-289/src/it/project/pom.xml
- src/it/MINVOKER-289/src/it/project/prebuild.bsh
- src/it/MINVOKER-289/verify.groovy
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
> [MINVOKER-289] - Support for shared invoker's Update-Snapshots Flag

- .github/workflows/maven-verify.yml
- Jenkinsfile
- pom.xml
- src/it/MINVOKER-196_junit_report_file/src/it/project/verify.groovy
- src/it/MINVOKER-196_junit_report_file/verify.groovy
- src/it/MINVOKER-288-failed-setup-run/verify.groovy
- src/it/MINVOKER-288-failed-setup-verify/verify.groovy
- src/it/local-repo-url/src/it/project/postbuild.groovy
- src/it/script-classpath-duplicates/pom.xml
- src/it/script-streamLogs-false/verify.groovy
- src/it/script-verify-xml/verify.groovy
- src/it/selector-scripts/setup.groovy
- src/it/settings-merge_jdk9+/src/it/project/postbuild.groovy
- src/site/apt/groovy-version.apt.vm
> [MINVOKER-312] change to groovy groupId org.apache.groovy and bump version to 4.x support jdk19

- pom.xml
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/CompositeMap.java
- src/main/java/org/apache/maven/plugins/invoker/FileLogger.java
- src/main/java/org/apache/maven/plugins/invoker/InstallMojo.java
- src/main/java/org/apache/maven/plugins/invoker/IntegrationTestMojo.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerReport.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerSession.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerToolchain.java
- src/main/java/org/apache/maven/plugins/invoker/JobExecutor.java
- src/main/java/org/apache/maven/plugins/invoker/MetadataUtils.java
- src/main/java/org/apache/maven/plugins/invoker/PomUtils.java
- src/main/java/org/apache/maven/plugins/invoker/ReportUtils.java
- src/main/java/org/apache/maven/plugins/invoker/RunFailureException.java
- src/main/java/org/apache/maven/plugins/invoker/Selector.java
- src/main/java/org/apache/maven/plugins/invoker/SelectorUtils.java
- src/main/java/org/apache/maven/plugins/invoker/SystemPropertyPrinter.java
- src/main/java/org/apache/maven/plugins/invoker/VerifyMojo.java
- src/test/java/org/apache/maven/plugins/invoker/ExtendedMavenProjectStub.java
- src/test/java/org/apache/maven/plugins/invoker/InterpolationTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerMojoTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerSessionTest.java
- src/test/java/org/apache/maven/plugins/invoker/JobExecutorTest.java
- src/test/java/org/apache/maven/plugins/invoker/SelectorTest.java
- src/test/java/org/apache/maven/plugins/invoker/SelectorUtilsTest.java
> upgrade to parent 39

- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerReport.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
If your pull request …
> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

- src/main/java/org/apache/maven/plugins/invoker/SelectorUtils.java
- Removed unused code
- Improved code.
> - Removed negative logic

- pom.xml
https://issues.apache.org/jira/browse/MINVOKER-337
> [MINVOKER-337] Exclude plexus-container-default and o.a.maven from runtime dependencies

- pom.xml
- src/it/exec-timeout-invoker-level/pom.xml
- src/it/exec-timeout-mojo-level/pom.xml
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerReport.java
- src/main/java/org/apache/maven/plugins/invoker/InvokerSession.java
- src/main/java/org/apache/maven/plugins/invoker/PomUtils.java
- src/main/java/org/apache/maven/plugins/invoker/VerifyMojo.java
- src/test/java/org/apache/maven/plugins/invoker/AbstractTestUtil.java
- src/test/java/org/apache/maven/plugins/invoker/InterpolationTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerMojoTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
- src/test/java/org/apache/maven/plugins/invoker/InvokerSessionTest.java
- src/test/java/org/apache/maven/plugins/invoker/JobExecutorTest.java
- src/test/java/org/apache/maven/plugins/invoker/SelectorTest.java
- src/test/java/org/apache/maven/plugins/invoker/SelectorUtilsTest.java
https://issues.apache.org/jira/browse/MINVOKER-284
> [MINVOKER-284] Switch to JUnit5, drop maven-compat

- src/it/MINVOKER-335-symlinks-in-source/invoker.properties
- src/it/MINVOKER-335-symlinks-in-source/pom.xml
- src/it/MINVOKER-335-symlinks-in-source/setup.groovy
- src/it/MINVOKER-335-symlinks-in-source/src/it/clone-symlinks/pom.xml
- src/it/MINVOKER-335-symlinks-in-source/verify.groovy
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
https://issues.apache.org/jira/browse/MINVOKER-335
> [MINVOKER-335] Preserve symlinks for copied files

- src/it/clone-clean/setup.groovy
- src/it/clone-clean/verify.groovy
- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
https://issues.apache.org/jira/browse/MINVOKER-336
> [MINVOKER-336] Create empty .mvn directory in cloned projects

- pom.xml
- src/it/invoker-report/verify.bsh
- src/main/java/org/apache/maven/plugins/invoker/InvokerReport.java
> [MINVOKER-354] Upgrade to Doxia 2.0.0 Milestone Stack

- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
JIRA issue: [MINVOKER-374](https://issues.apache.org/jira/browse/MINVOKER-374)
This is required for [Maven XInclude extension](https://github.com/apache/maven-xinclude-extension) which has pom files which cannot be parsed by stock maven (that's the whole point of the extension).
The invoker plugin loads the POMs to find which files need to be filtered and thus cause the plugin execution to fail.
> [MINVOKER-374] Ability to skip project collection

- src/main/java/org/apache/maven/plugins/invoker/InvokerSession.java
> Specify UTF-8 when reading build log

- src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
- src/site/apt/examples/filtering.apt.vm
It took me a while to figure out why filtering didn't work. This happened on a maven-enforcer rule project, 
so the `cloneProjectsTo` property was not set automatically (in contrast to maven-plugin projects).
> Add note about cloneProjectsTo being required for filtering
