src/it/project-setup/src/it/project3/invoker.properties, src/it/project-setup/src/it/project6/invoker.properties, src/it/project-setup/src/it/project6/pom.xml, src/it/project-setup/verify.bsh, src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java, src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java, src/main/java/org/apache/maven/plugins/invoker/InvokerSession.java, src/main/mdo/invocation.mdo, src/test/java/org/apache/maven/plugins/invoker/InvokerMojoTest.java
Signed-off-by: olivier lamy <olamy@apache.org>
=> [MINVOKER-174] add a property to configure build order

pom.xml
=> [MINVOKER-259] update doxia

src/it/updateOnly/pom.xml, src/it/updateOnly/src/it/project/pom.xml, src/it/updateOnly/verify.bsh, src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java
=> [MINVOKER-268] - Introduce updateOnly parameter to AbstractInvokerMojo

pom.xml
It is the last occurrence of ci-builds 😄
=> Fix jenkins address in ciManagement

pom.xml
=> [MINVOKER-298] Upgrade Maven Reporting to 3.1.0

src/it/MINVOKER-294-mavenExacutable-in-properties/pom.xml, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/invoker.properties, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/mvn1, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/mvn1.cmd, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/mvn2, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/mvn2.cmd, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/pom.xml, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/postbuild.groovy, src/it/MINVOKER-294-mavenExacutable-in-properties/src/it/project/prebuild.groovy, src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java, src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java, src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
=> [MINVOKER-294] Allow override mavenExecutable in invoker.properties

src/main/java/org/apache/maven/plugins/invoker/InvokerMojo.java, src/main/java/org/apache/maven/plugins/invoker/InvokerSession.java, src/main/java/org/apache/maven/plugins/invoker/VerifyMojo.java
=> [MINVOKER-303] Print build summary at the end after logs

pom.xml, src/it/script-classpath-duplicates/pom.xml, src/site/apt/groovy-version.apt.vm, src/site/site.xml
=> [MINVOKER-304] Use only common groovy modules - xml, json

pom.xml
=> [MINVOKER-310] Upgrade Parent to 37

pom.xml
=> merge back branch release-3.4.0

.github/workflows/maven-verify.yml, Jenkinsfile, pom.xml
=> build with jdk19

src/it/MINVOKER-328_install-default/invoker.properties, src/it/MINVOKER-328_install-default/pom.xml, src/it/MINVOKER-328_install-default/verify.groovy, src/main/java/org/apache/maven/plugins/invoker/InstallMojo.java
When user not specified localRepositoryPath
we can not reinstall artifact with the same source and target path
---
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if …
=> [MINVOKER-328] Skip install artifacts with the same source and target path

src/it/MINVOKER-330-realative-mavenExacutable/pom.xml, src/it/MINVOKER-330-realative-mavenExacutable/src/it/project/pom.xml, src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java, src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java, src/test/java/org/apache/maven/plugins/invoker/InvokerPropertiesTest.java
=> [MINVOKER-330] Allow relative path for mavenExecutable

pom.xml, src/it/invocation-debug/src/it/minvoker-142/verify.groovy, src/it/spaces-should-work_non-windows/src/it/minvoker-test/verify.groovy, src/it/spaces-should-work_windows/src/it/minvoker-test/verify.groovy, src/it/special-characters-should-work/src/it/minvoker-test/verify.groovy
=> [MINVOKER-332] Update plugins versions used in ITs

src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java, src/main/mdo/invocation.mdo
=> [MINVOKER-342] Use ChoiceFormat to selectively render elapsed time in AbstractInvokerMojo

pom.xml, src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java, src/main/java/org/apache/maven/plugins/invoker/InvokerProperties.java, src/main/java/org/apache/maven/plugins/invoker/SelectorUtils.java
- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MINVOKER) filed 
please …
=> [MINVOKER-352] - Remove usage commons-lang3

pom.xml
https://issues.apache.org/jira/browse/MINVOKER-366
=> [MINVOKER-366] Require Maven 3.6.3

pom.xml, src/main/java/org/apache/maven/plugins/invoker/AbstractInvokerMojo.java, src/main/java/org/apache/maven/plugins/invoker/InterpolatorUtils.java, src/test/java/org/apache/maven/plugins/invoker/InterpolatorUtilsTest.java, src/test/java/org/apache/maven/plugins/invoker/InvokerMojoTest.java
https://issues.apache.org/jira/browse/MINVOKER-307
=> [MINVOKER-307] Support `@{..}` syntax in mavenOpts

src/it/MINVOKER-368-install-filter-scope/pom.xml, src/it/MINVOKER-368-install-filter-scope/verify.groovy, src/main/java/org/apache/maven/plugins/invoker/InstallMojo.java
https://issues.apache.org/jira/browse/MINVOKER-368
=> [MINVOKER-368] Filter artifacts by scope before resolving in install

pom.xml
This closes #261
To make clear that you license your contribution …
=> [MINVOKER-371] Upgrade to Doxia 2.0.0 GA Stack

.github/ISSUE_TEMPLATE/BUG.yml, .github/ISSUE_TEMPLATE/FEATURE.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, .github/workflows/pr-automation.yml, .github/workflows/stale.yml, README.md, pom.xml
* Release and milestones already there
=> Enable GH Issues

.github/workflows/maven-verify.yml
Following this checklist to help us incorporate your
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Enable build by Maven 4 on GitHub
